In [3]:
import numpy as np

X = np.array([
    [5.1, 3.5, 1.4, 0.2],
    [4.9, 3.0, 1.4, 0.2],
    [7.0, 3.2, 4.7, 1.4],
    [6.4, 3.2, 4.5, 1.5],
    [6.3, 3.3, 6.0, 2.5],
    [5.8, 2.7, 5.1, 1.9] ])

Y = np.array([
    [1, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 0, 1] ])

Xtranspose = X.transpose()
katsayilar = np.linalg.inv(Xtranspose.dot(X)).dot(Xtranspose).dot(Y)

yuvarlanmiskatsayilar = np.round(katsayilar, 2)

print("Regresyon Katsayıları:")
print(yuvarlanmiskatsayilar)

yeniörnek = np.array([5, 3.4, 1.5, 0.2])
tahminisinif = np.argmax(np.dot(yeniörnek, yuvarlanmiskatsayilar))

siniflistesi = ['A', 'B', 'C']
tahmin_edilen_sinif_etiketi = siniflistesi[tahminisinif]

print("Yeni örneğin sınıfı:", tahmin_edilen_sinif_etiketi)


Regresyon Katsayıları:
[[ 0.77 -0.55  0.18]
 [-0.31  0.25 -0.06]
 [-1.69  1.96 -0.84]
 [ 2.55 -3.7   2.09]]
Yeni örneğin sınıfı: A
